### ISSUE TITLE
Bug: smart contract not called after signing

### ISSUE THREAD

**Issue by joshma91** [openlawteam/openlaw-core#62] opened 2019-01-22 08:30 UTC
After signing a contract (I've tried both OpenLaw and MetaMask signing), the status is stuck on "Signature Record (pending)" despite the signing transaction showing as having been confirmed on Etherscan. Consequently, my smart contract call isn't executed.

This occurred on this draft: https://app.openlaw.io/template/Bill%20of%20Sale%20(tutorial), as well as others. 

![image](https://user-images.githubusercontent.com/9612111/51521683-2870c300-1ddc-11e9-87eb-7b88be4df8d1.png)

Thanks!

**Comment by outkaj** [comment] 2019-01-29 18:53
Given that the transaction later went through, and given that we've tried to reproduce and haven't noticed any issues lately when testing smart contract executions for other issues, this may be due to network delays for example on Rinkeby. Closing for now, but feel free to re-open if you run into any similar such issues @joshma91.

**Comment by joshma91** [comment] 2019-06-05 19:06
Hi @outkaj, I'm re-opening this because I'm experiencing the same problem with this contract execution:
https://app.openlaw.io/contract/ed4c62745ad0de8d58613a6ca623d0508c42f09e77478b52d1e1f8a70ed00909?accessToken=51681e69-4d16-4a51-9b85-1273306ff4bc

The transaction hashes don't seem to have been broadcasted to Rinkeby, so would this suggest an issue with the OpenLaw VM?
https://rinkeby.etherscan.io/tx/0x02c3e64b5cc1da5866c14acc49cfd2dabcdf01f60888f5305f7b0bff07cb54b2

**Comment by outkaj** [comment] 2019-06-05 19:10
Hi @joshma91, thanks for re-opening! We have noticed this issue and are currently testing out some fixes for it. Cheers!

**Comment by outkaj** [comment] 2019-07-17 23:06
closing as @joshma91 confirmed this issue is now resolved

**Closed by outkaj** 2019-07-17 23:06 UTC
