### ISSUE TITLE
Bug: All Draft Versions Showing in Search

### ISSUE THREAD

**Issue by rachelob** [openlawteam/openlaw-core#54] opened 2019-01-15 17:18 UTC
All versions of the contract drafts are showing up in the 'Draft Management' section of the App and all with the timestamp of the most recent draft. 
Previously, only the most recent draft would appear and you could view other versions from that - which was much more manageable. 

<img width="1300" alt="screenshot 2019-01-15 at 16 56 48" src="https://user-images.githubusercontent.com/42391830/51197364-3fe61280-18e9-11e9-9008-b9409cd8546f.png">

**Comment by outkaj** [comment] 2019-01-25 14:20
@rachelob as I see it, there are two parts to this issue.

1) All versions of drafts are appearing - this is actually intended behavior. Every time you hit "Send Draft" a new draft is generated and they will all show up in the draft management page. 

2) All versions show with same timestamp - that sounds like a bug. We just did a new release yesterday and I have double-checked and could not reproduce the issue. Do you mind checking again and let me know if you still have the issue?

Thank you!

**Comment by atgrif** [comment] 2019-01-25 16:09
Hi @ShayShayBeekay , do you have time for a quick slack or zoom call? anne.griffin@openlaw.io.

**Comment by outkaj** [comment] 2019-03-15 19:34
Closing as we did not hear back from the reporter of the issue.

**Closed by outkaj** 2019-03-15 19:34 UTC
